services:
  cockatoo-gateway:
    build:
      context: ./CockatooGateway
      dockerfile: Dockerfile
    container_name: cockatoo-gateway
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - BETTERSTACK_SOURCETOKEN=${BETTERSTACK_SOURCETOKEN}
      - BETTERSTACK_ENDPOINT=${BETTERSTACK_ENDPOINT}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
